In [1]:
import ind_ec_data_scrapper as sc

In [2]:
df = sc.get_coalition_parties(2026, "West Bengal")
df.head()

                                        Party_Name               Coalition
16  All India Majlis-e-Ittehadul Muslimeen (AIMIM)               AIMIM-led
17                        Aam Janata Unnayan Party               AIMIM-led
18              Communist Party of India (Marxist)  Left–Congress alliance
19                        Communist Party of India  Left–Congress alliance
20                          All India Forward Bloc  Left–Congress alliance

In [3]:
d = sc.get_state_details("West Bengal")
print(d)

{'State': 'West Bengal', 'State_Code': 'WB', 'Assembly_Seats': 294}

In [4]:
print(sc.get_base_url("West Bengal", 2026))

https://results.eci.gov.in/ResultAcGenMay2026/ConstituencywiseS25

In [8]:
df = sc.get_state_constituency_details("west bengal")
df.head()

     Constituency_Num     District Constituency_Category
243                 1  Cooch Behar                    SC
244                 2  Cooch Behar                    SC
245                 3  Cooch Behar                    SC
246                 4  Cooch Behar               General
247                 5  Cooch Behar                    SC

In [9]:
sc.load_results_to_db("West Bengal", 2026)

202605082127: Starting West Bengal Election Data Scrapper for 2026 Elections...
Scraping data for constituency number 1 ...
Scraping data for constituency number 2 ...
Scraping data for constituency number 3 ...
Scraping data for constituency number 4 ...
Scraping data for constituency number 5 ...
Scraping data for constituency number 6 ...
Scraping data for constituency number 7 ...
Scraping data for constituency number 8 ...
Scraping data for constituency number 9 ...
Scraping data for constituency number 10 ...
Scraping data for constituency number 11 ...
Scraping data for constituency number 12 ...
Scraping data for constituency number 13 ...
Scraping data for constituency number 14 ...
Scraping data for constituency number 15 ...
Scraping data for constituency number 16 ...
Scraping data for constituency number 17 ...
Scraping data for constituency number 18 ...
Scraping data for constituency number 19 ...
Scraping data for constituency number 20 ...
Scraping data for constituency number 21 ...
Scraping data for constituency number 22 ...
Scraping data for constituency number 23 ...
Scraping data for constituency number 24 ...
Scraping data for constituency number 25 ...
Scraping data for constituency number 26 ...
Scraping data for constituency number 27 ...
Scraping data for constituency number 28 ...
Scraping data for constituency number 29 ...
Scraping data for constituency number 30 ...
Scraping data for constituency number 31 ...
Scraping data for constituency number 32 ...
Scraping data for constituency number 33 ...
Scraping data for constituency number 34 ...
Scraping data for constituency number 35 ...
Scraping data for constituency number 36 ...
Scraping data for constituency number 37 ...
Scraping data for constituency number 38 ...
Scraping data for constituency number 39 ...
Scraping data for constituency number 40 ...
Scraping data for constituency number 41 ...
Scraping data for constituency number 42 ...
Scraping data for constituency number 43 ...
Scraping data for constituency number 44 ...
Scraping data for constituency number 45 ...
Scraping data for constituency number 46 ...
Scraping data for constituency number 47 ...
Scraping data for constituency number 48 ...
Scraping data for constituency number 49 ...
Scraping data for constituency number 50 ...
Scraping data for constituency number 51 ...
Scraping data for constituency number 52 ...
Scraping data for constituency number 53 ...
Scraping data for constituency number 54 ...
Scraping data for constituency number 55 ...
Scraping data for constituency number 56 ...
Scraping data for constituency number 57 ...
Scraping data for constituency number 58 ...
Scraping data for constituency number 59 ...
Scraping data for constituency number 60 ...
Scraping data for constituency number 61 ...
Scraping data for constituency number 62 ...
Scraping data for constituency number 63 ...
Scraping data for constituency number 64 ...
Scraping data for constituency number 65 ...
Scraping data for constituency number 66 ...
Scraping data for constituency number 67 ...
Scraping data for constituency number 68 ...
Scraping data for constituency number 69 ...
Scraping data for constituency number 70 ...
Scraping data for constituency number 71 ...
Scraping data for constituency number 72 ...
Scraping data for constituency number 73 ...
Scraping data for constituency number 74 ...
Scraping data for constituency number 75 ...
Scraping data for constituency number 76 ...
Scraping data for constituency number 77 ...
Scraping data for constituency number 78 ...
Scraping data for constituency number 79 ...
Scraping data for constituency number 80 ...
Scraping data for constituency number 81 ...
Scraping data for constituency number 82 ...
Scraping data for constituency number 83 ...
Scraping data for constituency number 84 ...
Scraping data for constituency number 85 ...
Scraping data for constituency number 86 ...
Scraping data for constituency number 87 ...
Scraping data for constituency number 88 ...
Scraping data for constituency number 89 ...
Scraping data for constituency number 90 ...
Scraping data for constituency number 91 ...
Scraping data for constituency number 92 ...
Scraping data for constituency number 93 ...
Scraping data for constituency number 94 ...
Scraping data for constituency number 95 ...
Scraping data for constituency number 96 ...
Scraping data for constituency number 97 ...
Scraping data for constituency number 98 ...
Scraping data for constituency number 99 ...
Scraping data for constituency number 100 ...
Scraping data for constituency number 101 ...
Scraping data for constituency number 102 ...
Scraping data for constituency number 103 ...
Scraping data for constituency number 104 ...
Scraping data for constituency number 105 ...
Scraping data for constituency number 106 ...
Scraping data for constituency number 107 ...
Scraping data for constituency number 108 ...
Scraping data for constituency number 109 ...
Scraping data for constituency number 110 ...
Scraping data for constituency number 111 ...
Scraping data for constituency number 112 ...
Scraping data for constituency number 113 ...
Scraping data for constituency number 114 ...
Scraping data for constituency number 115 ...
Scraping data for constituency number 116 ...
Scraping data for constituency number 117 ...
Scraping data for constituency number 118 ...
Scraping data for constituency number 119 ...
Scraping data for constituency number 120 ...
Scraping data for constituency number 121 ...
Scraping data for constituency number 122 ...
Scraping data for constituency number 123 ...
Scraping data for constituency number 124 ...
Scraping data for constituency number 125 ...
Scraping data for constituency number 126 ...
Scraping data for constituency number 127 ...
Scraping data for constituency number 128 ...
Scraping data for constituency number 129 ...
Scraping data for constituency number 130 ...
Scraping data for constituency number 131 ...
Scraping data for constituency number 132 ...
Scraping data for constituency number 133 ...
Scraping data for constituency number 134 ...
Scraping data for constituency number 135 ...
Scraping data for constituency number 136 ...
Scraping data for constituency number 137 ...
Scraping data for constituency number 138 ...
Scraping data for constituency number 139 ...
Scraping data for constituency number 140 ...
Scraping data for constituency number 141 ...
Scraping data for constituency number 142 ...
Scraping data for constituency number 143 ...
Scraping data for constituency number 144 ...
Scraping data for constituency number 145 ...
Scraping data for constituency number 146 ...
Scraping data for constituency number 147 ...
Scraping data for constituency number 148 ...
Scraping data for constituency number 149 ...
Scraping data for constituency number 150 ...
Scraping data for constituency number 151 ...
Scraping data for constituency number 152 ...
Scraping data for constituency number 153 ...
Scraping data for constituency number 154 ...
Scraping data for constituency number 155 ...
Scraping data for constituency number 156 ...
Scraping data for constituency number 157 ...
Scraping data for constituency number 158 ...
Scraping data for constituency number 159 ...
Scraping data for constituency number 160 ...
Scraping data for constituency number 161 ...
Scraping data for constituency number 162 ...
Scraping data for constituency number 163 ...
Scraping data for constituency number 164 ...
Scraping data for constituency number 165 ...
Scraping data for constituency number 166 ...
Scraping data for constituency number 167 ...
Scraping data for constituency number 168 ...
Scraping data for constituency number 169 ...
Scraping data for constituency number 170 ...
Scraping data for constituency number 171 ...
Scraping data for constituency number 172 ...
Scraping data for constituency number 173 ...
Scraping data for constituency number 174 ...
Scraping data for constituency number 175 ...
Scraping data for constituency number 176 ...
Scraping data for constituency number 177 ...
Scraping data for constituency number 178 ...
Scraping data for constituency number 179 ...
Scraping data for constituency number 180 ...
Scraping data for constituency number 181 ...
Scraping data for constituency number 182 ...
Scraping data for constituency number 183 ...
Scraping data for constituency number 184 ...
Scraping data for constituency number 185 ...
Scraping data for constituency number 186 ...
Scraping data for constituency number 187 ...
Scraping data for constituency number 188 ...
Scraping data for constituency number 189 ...
Scraping data for constituency number 190 ...
Scraping data for constituency number 191 ...
Scraping data for constituency number 192 ...
Scraping data for constituency number 193 ...
Scraping data for constituency number 194 ...
Scraping data for constituency number 195 ...
Scraping data for constituency number 196 ...
Scraping data for constituency number 197 ...
Scraping data for constituency number 198 ...
Scraping data for constituency number 199 ...
Scraping data for constituency number 200 ...
Scraping data for constituency number 201 ...
Scraping data for constituency number 202 ...
Scraping data for constituency number 203 ...
Scraping data for constituency number 204 ...
Scraping data for constituency number 205 ...
Scraping data for constituency number 206 ...
Scraping data for constituency number 207 ...
Scraping data for constituency number 208 ...
Scraping data for constituency number 209 ...
Scraping data for constituency number 210 ...
Scraping data for constituency number 211 ...
Scraping data for constituency number 212 ...
Scraping data for constituency number 213 ...
Scraping data for constituency number 214 ...
Scraping data for constituency number 215 ...
Scraping data for constituency number 216 ...
Scraping data for constituency number 217 ...
Scraping data for constituency number 218 ...
Scraping data for constituency number 219 ...
Scraping data for constituency number 220 ...
Scraping data for constituency number 221 ...
Scraping data for constituency number 222 ...
Scraping data for constituency number 223 ...
Scraping data for constituency number 224 ...
Scraping data for constituency number 225 ...
Scraping data for constituency number 226 ...
Scraping data for constituency number 227 ...
Scraping data for constituency number 228 ...
Scraping data for constituency number 229 ...
Scraping data for constituency number 230 ...
Scraping data for constituency number 231 ...
Scraping data for constituency number 232 ...
Scraping data for constituency number 233 ...
Scraping data for constituency number 234 ...
Scraping data for constituency number 235 ...
Scraping data for constituency number 236 ...
Scraping data for constituency number 237 ...
Scraping data for constituency number 238 ...
Scraping data for constituency number 239 ...
Scraping data for constituency number 240 ...
Scraping data for constituency number 241 ...
Scraping data for constituency number 242 ...
Scraping data for constituency number 243 ...
Scraping data for constituency number 244 ...
Scraping data for constituency number 245 ...
Scraping data for constituency number 246 ...
Scraping data for constituency number 247 ...
Scraping data for constituency number 248 ...
Scraping data for constituency number 249 ...
Scraping data for constituency number 250 ...
Scraping data for constituency number 251 ...
Scraping data for constituency number 252 ...
Scraping data for constituency number 253 ...
Scraping data for constituency number 254 ...
Scraping data for constituency number 255 ...
Scraping data for constituency number 256 ...
Scraping data for constituency number 257 ...
Scraping data for constituency number 258 ...
Scraping data for constituency number 259 ...
Scraping data for constituency number 260 ...
Scraping data for constituency number 261 ...
Scraping data for constituency number 262 ...
Scraping data for constituency number 263 ...
Scraping data for constituency number 264 ...
Scraping data for constituency number 265 ...
Scraping data for constituency number 266 ...
Scraping data for constituency number 267 ...
Scraping data for constituency number 268 ...
Scraping data for constituency number 269 ...
Scraping data for constituency number 270 ...
Scraping data for constituency number 271 ...
Scraping data for constituency number 272 ...
Scraping data for constituency number 273 ...
Scraping data for constituency number 274 ...
Scraping data for constituency number 275 ...
Scraping data for constituency number 276 ...
Scraping data for constituency number 277 ...
Scraping data for constituency number 278 ...
Scraping data for constituency number 279 ...
Scraping data for constituency number 280 ...
Scraping data for constituency number 281 ...
Scraping data for constituency number 282 ...
Scraping data for constituency number 283 ...
Scraping data for constituency number 284 ...
Scraping data for constituency number 285 ...
Scraping data for constituency number 286 ...
Scraping data for constituency number 287 ...
Scraping data for constituency number 288 ...
Scraping data for constituency number 289 ...
Scraping data for constituency number 290 ...
Scraping data for constituency number 291 ...
Scraping data for constituency number 292 ...
Scraping data for constituency number 293 ...
Scraping data for constituency number 294 ...
202605082131: West Bengal Election Data Scrapper completed successfully. Data saved to 'west bengal_election_results_202605082127.csv'.
204

In [ ]:
import pandas as pd
cd = pd.read_csv("data/constituency_details.csv")
cd.head()

,State,District,Constituency_Num,Constituency_Name,Constituency_Category
0,Bihar,Paschim Champaran,1,Valmiki Nagar,General
1,Bihar,Paschim Champaran,2,Ramnagar,SC
2,Bihar,Paschim Champaran,3,Narkatiaganj,General
3,Bihar,Paschim Champaran,4,Bagaha,General
4,Bihar,Paschim Champaran,5,Lauriya,General

In [ ]:
def get_state_constituency_details(state: str) -> pd.DataFrame:
    state = state.title()
    df = pd.read_csv("data/constituency_details.csv")
    df = df[["Constituency_Num", "District", "Constituency_Category"]]

    return df

In [ ]:
cd = get_state_constituency_details("bihar")
cd.head()

   Constituency_Num           District Constituency_Category
0                 1  Paschim Champaran               General
1                 2  Paschim Champaran                    SC
2                 3  Paschim Champaran               General
3                 4  Paschim Champaran               General
4                 5  Paschim Champaran               General

In [ ]:
cd = cd[["Constituency_Num", "District", "Constituency_Category"]]

cd.head()

   Constituency_Num           District Constituency_Category
0                 1  Paschim Champaran               General
1                 2  Paschim Champaran                    SC
2                 3  Paschim Champaran               General
3                 4  Paschim Champaran               General
4                 5  Paschim Champaran               General

In [ ]:
df_with_dist = df.merge(cd, left_on="Constituency_Num", right_on="Constituency_Num", how="left")
df_with_dist.head(100)

,Constituency_Num,Constituency_Name,Serial_Num,Candidate_Name,Party_Name,EVM_Votes,Postal_Votes,Total_Votes,Vote_Percent,Total_Rounds,Current_Round,State,District_x,Constituency_Category_x,District_y,Constituency_Category_y
0,1,Valmiki Nagar,1,Dhirendra Pratap Singh Alias Rinku Singh,Janata Dal (United),105771,284,106055,45.39,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General
1,1,Valmiki Nagar,2,Rameshwar Yadav,Bahujan Samaj Party,5294,18,5312,2.27,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General
2,1,Valmiki Nagar,3,Surendra Prasad,Indian National Congress,107374,356,107730,46.11,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General
3,1,Valmiki Nagar,4,Rajesh Sharma,Lok Samaj Party,2301,2,2303,0.99,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General
4,1,Valmiki Nagar,5,Azharuddin Ansari,Independent,1553,1,1554,0.67,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General
5,1,Valmiki Nagar,6,Mahmad Jalil,Independent,2426,0,2426,1.04,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General
6,1,Valmiki Nagar,7,Surendra Ram,Independent,1850,2,1852,0.79,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General
7,1,Valmiki Nagar,8,Nota,None of the Above,6391,9,6400,2.74,32,32,Bihar,Paschim Champaran,General,Paschim Champaran,General